const sb = window.supabaseClient;
const $ = id => document.getElementById(id);
let session=null, profile=null, settings={name:'BARBERÍA',yape_number:'',yape_name:'',qr_path:null};
let barbers=[], services=[], cuts=[];
let selectedCutServices=[];
const today=()=>new Date().toISOString().slice(0,10);
const money=n=>`S/ ${Number(n||0).toFixed(2)}`;
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2500)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function init(){
  const {data:{session:s}}=await sb.auth.getSession(); if(s) await enter(s); else showLogin();
  sb.auth.onAuthStateChange(async(_,s)=>{if(s) await enter(s); else showLogin()});
  $('loginForm').addEventListener('submit',login); $('logoutBtn').addEventListener('click',()=>sb.auth.signOut()); $('mobileLogout').addEventListener('click',()=>sb.auth.signOut());
  document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
  document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));
  $('cutService').addEventListener('change',updatePrice); $('cutPayment').addEventListener('change',()=>{}); $('cutForm').addEventListener('submit',registerCut);
  $('addCutService').addEventListener('click',addCutService); $('selectedServices').addEventListener('click',e=>{const button=e.target.closest('[data-remove-service]');if(button){selectedCutServices.splice(Number(button.dataset.removeService),1);renderSelectedServices(true)}}); $('cutPrice').addEventListener('input',updateEarnings);
  $('closeQr').addEventListener('click',()=>$('qrDialog').close()); $('qrDialog').addEventListener('click',e=>{if(e.target===$('qrDialog'))$('qrDialog').close()});
  $('barberForm').addEventListener('submit',saveBarber); $('serviceForm').addEventListener('submit',saveService); $('serviceCancel').addEventListener('click',resetServiceForm); $('settingsForm').addEventListener('submit',saveSettings);
  $('exportBtn').addEventListener('click',exportExcel); ['filterDate','filterBarber','filterPayment'].forEach(id=>$(id).addEventListener('change',renderHistory)); $('liquidDate').value=today(); $('liquidDate').addEventListener('change',renderLiquidations);
}
function showLogin(){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden')}
async function login(e){e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)toast(error.message)}
async function enter(s){session=s; $('loginView').classList.add('hidden');$('appView').classList.remove('hidden'); try{await loadAll()}catch(e){console.error(e);toast(e.message||'No se pudo cargar la app')}}
function isAdmin(){return profile?.role==='admin'}
async function loadAll(){
  const p=await sb.from('barberia_usuarios').select('*').eq('id',session.user.id).maybeSingle(); if(p.error) throw p.error; profile=p.data;
  if(!profile){toast('Tu usuario existe en Auth pero aún no tiene perfil en barberia_usuarios.');return}
  document.querySelectorAll('.admin-only').forEach(x=>x.classList.toggle('hidden',!isAdmin())); document.querySelectorAll('.barber-only').forEach(x=>x.classList.toggle('hidden',isAdmin()));
  $('profileMini').innerHTML=`<div class="profile-name"><strong>${esc(profile.name||session.user.email)}</strong><small>${esc(profile.role)}</small></div>`;
  $('roleBadge').textContent=profile.role==='admin'?'ADMINISTRADOR':'BARBERO'; $('todayLabel').textContent=new Date().toLocaleDateString('es-PE',{weekday:'long',year:'numeric',month:'long',day:'numeric'});$('welcomeName').textContent=`Hola, ${profile.name||'bienvenido'}`;
  await Promise.all([loadSettings(),loadBarbers(),loadServices(),loadCuts()]); renderDashboard(); renderHistory(); renderLiquidations();
}
async function loadSettings(){const {data,error}=await sb.from('barberia_config').select('*').limit(1).maybeSingle();if(error)throw error;if(data)settings=data;$('yapeNumber').textContent=settings.yape_number||'Configura tu número';if(settings.qr_path)await showQr(settings.qr_path);}
async function showQr(path){const {data,error}=await sb.storage.from('barberia-comprobantes').createSignedUrl(path,3600);if(!error&&data?.signedUrl){$('yapeQr').innerHTML=`<button class="qr-trigger" type="button" aria-label="Ampliar QR de Yape"><img class="qr-img" src="${data.signedUrl}" alt="QR Yape"><span>Toca para ampliar</span></button>`;$('currentQr').innerHTML=`<p>QR actual:</p><button class="qr-trigger" type="button" aria-label="Ampliar QR de Yape"><img class="qr-img" src="${data.signedUrl}" alt="QR Yape"><span>Toca para ampliar</span></button>`;document.querySelectorAll('.qr-trigger').forEach(b=>b.addEventListener('click',()=>{$('largeQr').src=data.signedUrl;$('qrDialog').showModal()}))}}
async function loadBarbers(){const {data,error}=await sb.from('barberia_usuarios').select('*').eq('role','barbero').eq('active',true).order('name');if(error)throw error;barbers=data||[];fillBarberSelects();renderBarbers()}
async function loadServices(){const {data,error}=await sb.from('barberia_servicios').select('*').order('name');if(error)throw error;services=data||[];fillServices();renderServices()}
async function loadCuts(){let q=sb.from('barberia_cortes').select('*, barber:barberia_usuarios!barber_id(name), service:barberia_servicios!service_id(name)').order('created_at',{ascending:false});const {data,error}=await q.limit(1000);if(error)throw error;cuts=data||[]}
function fillBarberSelects(){$('filterBarber').innerHTML='<option value="">Todos los barberos</option>'+barbers.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}
function fillServices(){$('cutService').innerHTML=services.filter(s=>s.active).map(s=>`<option value="${s.id}" data-price="${s.price}">${esc(s.name)} — ${money(s.price)}</option>`).join('');updatePrice()}
function serviceGoesToBarber(service){return /barba|ceja/i.test(service?.name||'')}
function addCutService(){const service=services.find(s=>s.id===$('cutService').value);if(!service)return;if(selectedCutServices.some(s=>s.id===service.id))return toast('Ese servicio ya está agregado');selectedCutServices.push(service);renderSelectedServices(true)}
function renderSelectedServices(resetTotal=false){$('selectedServices').innerHTML=selectedCutServices.map((s,i)=>`<span class="selected-service">${esc(s.name)} · ${money(s.price)} <button type="button" data-remove-service="${i}" aria-label="Quitar ${esc(s.name)}">×</button></span>`).join('')||'<small>Agrega uno o varios servicios.</small>';if(resetTotal)$('cutPrice').value=selectedCutServices.reduce((sum,s)=>sum+Number(s.price),0).toFixed(2);updateEarnings()}
function updatePrice(){updateEarnings()}
function updateEarnings(){const total=Number($('cutPrice').value||0),baseTotal=selectedCutServices.reduce((sum,s)=>sum+Number(s.price),0),barber=barbers.find(x=>x.id===session?.user?.id),defaultPct=Number(barber?.commission_percent??50);const barberPct=baseTotal?selectedCutServices.reduce((sum,s)=>sum+Number(s.price)*(serviceGoesToBarber(s)?100:defaultPct),0)/baseTotal:0;$('cutCommission').value=selectedCutServices.some(serviceGoesToBarber)?`${barberPct.toFixed(0)}% aprox.`:`${defaultPct}%`;$('cutBarberEarn').value=money(total*barberPct/100);$('cutShopEarn').value=money(total-total*barberPct/100)}
async function registerCut(e){e.preventDefault();if(isAdmin())return toast('Inicia sesión con la cuenta del barbero que realizó el servicio');const barber=barbers.find(b=>b.id===session?.user?.id),total=Number($('cutPrice').value);if(!barber)return toast('No se encontró tu perfil activo de barbero');if(!selectedCutServices.length)return toast('Agrega al menos un servicio');if(!Number.isFinite(total)||total<0)return toast('Ingresa un total válido');let receipt_path=null;const file=$('cutReceipt').files[0];if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${barber.id}/${Date.now()}.${ext}`;const up=await sb.storage.from('barberia-comprobantes').upload(path,file,{upsert:false,contentType:file.type});if(up.error){toast(up.error.message);return}receipt_path=path}const {error}=await sb.rpc('barberia_registrar_servicios', {p_barber_id:session.user.id,p_items:selectedCutServices.map(s=>({service_id:s.id,price:s.price})),p_total:total,p_payment_method:$('cutPayment').value,p_receipt_path:receipt_path});if(error){toast(error.message);return}toast('Servicios registrados a tu nombre');e.target.reset();selectedCutServices=[];renderSelectedServices();$('cutPayment').value='yape';await loadCuts();renderDashboard();renderHistory();renderLiquidations();updatePrice()}
function renderDashboard(){const d=today(),day=cuts.filter(c=>c.created_at?.slice(0,10)===d);$('statCuts').textContent=day.length;$('statSales').textContent=money(day.reduce((a,c)=>a+Number(c.price),0));$('statShop').textContent=money(day.reduce((a,c)=>a+Number(c.shop_amount),0));$('statCommissions').textContent=money(day.reduce((a,c)=>a+Number(c.barber_amount),0));const counts=(isAdmin()?barbers:barbers.filter(b=>b.id===session?.user?.id)).map(b=>({b,n:day.filter(c=>c.barber_id===b.id).length}));const max=Math.max(1,...counts.map(x=>x.n));$('activityTitle').textContent=isAdmin()?'Cortes por barbero':'Mi actividad';$('commissionLabel').textContent=isAdmin()?'COMISIONES DEL EQUIPO':'MIS COMISIONES';$('barberStats').innerHTML=counts.length?counts.map(x=>`<div class="barber-row"><div class="barber-line"><span>${esc(x.b.name)}</span><strong>${x.n} cortes</strong></div><div class="bar"><i style="width:${x.n/max*100}%"></i></div></div>`).join(''):'<p>Sin actividad registrada hoy.</p>'}
async function receiptLink(path){if(!path)return '-';const {data,error}=await sb.storage.from('barberia-comprobantes').createSignedUrl(path,600);return error?'-':`<a class="receipt" target="_blank" href="${data.signedUrl}">Ver foto</a>`}
async function renderHistory(){const date=$('filterDate').value, bid=$('filterBarber').value,pay=$('filterPayment').value;let rows=cuts;if(date)rows=rows.filter(c=>c.created_at?.slice(0,10)===date);if(bid)rows=rows.filter(c=>c.barber_id===bid);if(pay)rows=rows.filter(c=>c.payment_method===pay);$('historyBody').innerHTML='';for(const c of rows){const tr=document.createElement('tr');tr.innerHTML=`<td>${new Date(c.created_at).toLocaleString('es-PE')}</td><td>${esc(c.barber?.name)}</td><td>${esc(c.service?.name)}</td><td>${money(c.price)}</td><td>${money(c.barber_amount)}</td><td>${money(c.shop_amount)}</td><td><span class="pill">${esc(c.payment_method)}</span></td><td class="receipt-cell">...</td>`;$('historyBody').appendChild(tr);tr.querySelector('.receipt-cell').innerHTML=await receiptLink(c.receipt_path)}}
function renderBarbers(){$('barbersBody').innerHTML=barbers.map(b=>`<tr><td>${esc(b.name)}</td><td>${esc(b.email||'-')}</td><td>${b.commission_percent}%</td><td><span class="pill">Activo</span></td></tr>`).join('')}
async function saveBarber(e){e.preventDefault();const {error}=await sb.from('barberia_usuarios').upsert({id:$('barberUserId').value.trim(),name:$('barberName').value.trim(),commission_percent:Number($('barberCommission').value),role:'barbero',email:null},{onConflict:'id'});if(error)toast(error.message);else{toast('Barbero guardado');e.target.reset();await loadBarbers();renderDashboard()}}
function renderServices(){$('servicesBody').innerHTML=services.map(s=>`<tr><td>${esc(s.name)}</td><td>${money(s.price)}</td><td><span class="pill">${s.active?'Activo':'Inactivo'}</span></td><td><button onclick="editService('${s.id}')">Editar</button> <button onclick="toggleService('${s.id}',${s.active})">${s.active?'Desactivar':'Activar'}</button></td></tr>`).join('')}
window.editService=(id)=>{const s=services.find(x=>x.id===id);if(!s)return;$('serviceId').value=s.id;$('serviceName').value=s.name;$('servicePrice').value=s.price;$('serviceSubmit').textContent='Guardar cambios';$('serviceCancel').classList.remove('hidden');$('serviceName').focus()}
function resetServiceForm(){$('serviceForm').reset();$('serviceId').value='';$('serviceSubmit').textContent='Agregar servicio';$('serviceCancel').classList.add('hidden')}
async function saveService(e){e.preventDefault();const id=$('serviceId').value,payload={name:$('serviceName').value.trim(),price:Number($('servicePrice').value)};const {error}=id?await sb.from('barberia_servicios').update(payload).eq('id',id):await sb.from('barberia_servicios').insert({...payload,active:true});if(error)toast(error.message);else{toast(id?'Servicio actualizado':'Servicio agregado');resetServiceForm();await loadServices()}}
window.toggleService=async(id,active)=>{const {error}=await sb.from('barberia_servicios').update({active:!active}).eq('id',id);if(error)toast(error.message);else await loadServices()}
function renderLiquidations(){if(!isAdmin())return;const d=$('liquidDate').value||today(),day=cuts.filter(c=>c.created_at?.slice(0,10)===d);$('liquidations').innerHTML=barbers.map(b=>{const rows=day.filter(c=>c.barber_id===b.id),sales=rows.reduce((a,c)=>a+Number(c.price),0),earn=rows.reduce((a,c)=>a+Number(c.barber_amount),0);return `<div class="liquid-card"><strong>${esc(b.name)}</strong><div class="liquid-meta"><div><small>Cortes</small><b>${rows.length}</b></div><div><small>Ventas</small><b>${money(sales)}</b></div><div><small>A recibir</small><b>${money(earn)}</b></div></div></div>`}).join('')||'<p>No hay barberos.</p>'}
async function saveSettings(e){e.preventDefault();let qr_path=settings.qr_path;const file=$('settingQr').files[0];if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`config/yape-${Date.now()}.${ext}`;const up=await sb.storage.from('barberia-comprobantes').upload(path,file,{contentType:file.type});if(up.error){toast(up.error.message);return}qr_path=path}const payload={id:settings.id||undefined,name:$('settingName').value.trim(),yape_number:$('settingYape').value.trim(),yape_name:$('settingYapeName').value.trim(),qr_path};const {data,error}=await sb.from('barberia_config').upsert(payload).select().single();if(error)toast(error.message);else{settings=data;toast('Configuración guardada');if(qr_path)await showQr(qr_path)}}
async function exportExcel(){const date=$('filterDate').value,bid=$('filterBarber').value,pay=$('filterPayment').value;let rows=cuts;if(date)rows=rows.filter(c=>c.created_at?.slice(0,10)===date);if(bid)rows=rows.filter(c=>c.barber_id===bid);if(pay)rows=rows.filter(c=>c.payment_method===pay);const data=rows.map(c=>({Fecha:new Date(c.created_at).toLocaleString('es-PE'),Barbero:c.barber?.name||'',Servicio:c.service?.name||'',Precio:Number(c.price),Comision:`${c.commission_percent}%`,Barbero_Gana:Number(c.barber_amount),Barberia_Gana:Number(c.shop_amount),Pago:c.payment_method,Comprobante:c.receipt_path?'Sí':'No'}));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Cortes');XLSX.writeFile(wb,`barberia-cortes-${date||'todos'}.xlsx`)}
function showPage(page){if(page==='corte'&&isAdmin()){toast('El registro de servicios está disponible desde la cuenta de cada barbero');page='dashboard'}document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('page-'+page).classList.remove('hidden');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={dashboard:'Inicio',corte:'Registrar corte',historial:'Historial',barberos:'Barberos',servicios:'Servicios',liquidaciones:'Liquidaciones',ajustes:'Configuración'};$('pageTitle').textContent=titles[page]||'Inicio';if(page==='liquidaciones')renderLiquidations();if(page==='ajustes'){ $('settingName').value=settings.name||'';$('settingYape').value=settings.yape_number||'';$('settingYapeName').value=settings.yape_name||''}}
document.addEventListener('DOMContentLoaded',init);
